
class DataframeDefine:
    
    columns = {
        "flow_abastecida_cavalo": {
            "cd_abastecimento": ["b:Codigo"],
            "nr_notafiscal": ["b:Documento"],
            "dt_emissao": ["b:Data"],
            "cd_relacionado": ["b:Posto", "c:CodigoIntegracao"],
            "ds_cnpjcpf": ["b:Posto", "c:CPFCNPJ"],
            "ds_ierg": ["b:Posto", "c:RGIE"],
            "ds_nomerazaosocial": ["b:Posto", "c:RazaoSocial"],
            "ds_nomefantasia": ["b:Posto", "c:NomeFantasia"],
            "ds_email": ["b:Posto", "c:Email"],
            "ds_telefone1": ["b:Posto", "c:Endereco", "d:Telefone"],
            "ds_telefone2": ["b:Posto", "c:Endereco", "d:Telefone2"],
            "ds_endereco": ["b:Posto", "c:Endereco", "d:Logradouro"],
            "ds_cep": ["b:Posto", "c:Endereco", "d:CEP"],
            "ds_latitude": ["b:Posto", "c:Endereco", "d:Latitude"],
            "ds_longitude": ["b:Posto", "c:Endereco", "d:Longitude"],
            "dt_nascfundacao": None,
            "ds_cidade": ["b:Posto", "c:Endereco", "d:Cidade", "e:Descricao"],
            "ds_uf": ["b:Posto", "c:Endereco", "d:Cidade", "e:SiglaUF"],
            "ds_pais": ["b:Posto", "c:Endereco", "d:Cidade", "e:Pais", "d:NomePais"],
            "ds_grupo": ["b:Posto", "c:NomeFantasia"],
            "cd_produto": ["b:Produto", "c:Codigo"],
            "ds_produto": ["b:Produto", "c:Descricao"],
            "ds_ncm": ["b:Produto", "c:NCM"],
            "ds_undmedida": None,
            "cd_veiculo": ["b:Veiculo", "b:Codigo"],
            "ds_placa": ["b:Veiculo", "b:Placa"],
            "ds_nrfrota": ["b:Veiculo", "b:NumeroFrota"],
            "ds_chassi": ["b:Veiculo", "b:NumeroChassi"],
            "ds_renavam": ["b:Veiculo", "b:Renavam"],
            "nr_anofabricacao": ["b:Veiculo", "b:AnoFabricacao"],
            "nr_anomodelo": ["b:Veiculo", "b:AnoModelo"],
            "ds_marca": ["b:Veiculo", "b:Modelo", "b:Marca", "b:Descricao"],
            "ds_modelo": ["b:Veiculo", "b:Modelo", "b:Descricao"],
            "ds_tipoveiculo": ["b:Veiculo", "b:TipoVeiculo"],
            "ds_frota": ["b:Veiculo", "b:SegmentoVeiculo", "b:Descricao"],
            "nr_frota": ["b:Veiculo", "b:NumeroFrota"],
            "dt_aquisicao": ["b:Veiculo", "b:DataAquisicao"],
            "nr_km": ["b:Kilometragem"],
            "nr_horimetro": ["b:Horimetro"],
            "nr_litros": ["b:Litros"],
            "nr_quantidade": ["b:Litros"],
            "nr_valorunitario": ["b:ValorUnitario"],
            "nr_preco": ["b:ValorUnitario"],
            "nr_valortotal": ["b:ValorTotal"],
            "cd_viagem": ["b:NumeroAcerto"],
            "cd_motorista": ["b:Motorista", "c:Codigo"],
            "ds_nomemotorista": ["b:Motorista", "c:Nome"],
            "ds_cpf":  ["b:Motorista", "c:CPF"],
            "ds_rg":  ["b:Motorista", "c:RG"],
            "dt_nascimento":  ["b:Motorista", "c:DataNascimento"],
            "ds_estadocivil":  ["b:Motorista", "c:EstadoCivil"],
            "ds_enderecomotorista":  ["b:Motorista", "c:Endereco", "d:Logradouro"],
            "ds_cidademotorista":  ["b:Motorista", "c:Endereco", "d:Cidade", "e:Descricao"],
            "ds_ufmotorista":  ["b:Motorista", "c:Endereco", "d:Cidade", "e:SiglaUF"],
            "ds_paismotorista": ["b:Motorista", "c:Endereco", "d:Cidade", "e:Pais", "d:NomePais"],
            "fl_ativo": None
        },
        "flow_abastecida_equipamento": {
            "cd_abastecimento": ["b:Codigo"],
            "nr_notafiscal": ["b:Documento"],
            "dt_emissao": ["b:Data"],
            "cd_relacionado": ["b:Posto", "c:CodigoIntegracao"],
            "ds_cnpjcpf": ["b:Posto", "c:CPFCNPJ"],
            "ds_ierg": ["b:Posto", "c:RGIE"],
            "ds_nomerazaosocial": ["b:Posto", "c:RazaoSocial"],
            "ds_nomefantasia": ["b:Posto", "c:NomeFantasia"],
            "ds_email": ["b:Posto", "c:Email"],
            "ds_telefone1": ["b:Posto", "c:Endereco", "d:Telefone"],
            "ds_telefone2": ["b:Posto", "c:Endereco", "d:Telefone2"],
            "ds_endereco": ["b:Posto", "c:Endereco", "d:Logradouro"],
            "ds_cep": ["b:Posto", "c:Endereco", "d:CEP"],
            "ds_latitude": ["b:Posto", "c:Endereco", "d:Latitude"],
            "ds_longitude": ["b:Posto", "c:Endereco", "d:Longitude"],
            "dt_nascfundacao": None,
            "ds_cidade": ["b:Posto", "c:Endereco", "d:Cidade", "e:Descricao"],
            "ds_uf": ["b:Posto", "c:Endereco", "d:Cidade", "e:SiglaUF"],
            "ds_pais": ["b:Posto", "c:Endereco", "d:Cidade", "e:Pais", "d:NomePais"],
            "ds_grupo": ["b:Posto", "c:NomeFantasia"],
            "cd_produto": ["b:Produto", "c:Codigo"],
            "ds_produto": ["b:Produto", "c:Descricao"],
            "ds_ncm": ["b:Produto", "c:NCM"],
            "ds_undmedida": None,
            "cd_veiculo": ["b:Equipamento", "b:Codigo"],
            "ds_placa": ["b:Equipamento", "b:Descricao"],
            "ds_nrfrota": ["b:Equipamento", "b:Numero"],
            "ds_chassi": None,
            "ds_renavam": None,
            "nr_anofabricacao": ["b:Equipamento", "b:AnoFabricacao"],
            "nr_anomodelo": ["b:Equipamento", "b:AnoModelo"],
            "ds_marca": ["b:Equipamento", "b:Marca"],
            "ds_modelo": ["b:Equipamento", "b:Modelo"],
            "ds_tipoveiculo": "EQUIPAMENTO",
            "ds_frota": ["b:Equipamento", "b:Segmento"],
            "nr_frota": ["b:Equipamento", "b:Numero"],
            "dt_aquisicao": ["b:Equipamento", "b:DataAquisicao"],
            "nr_km": ["b:Kilometragem"],
            "nr_horimetro": ["b:Horimetro"],
            "nr_litros": ["b:Litros"],
            "nr_quantidade": ["b:Litros"],
            "nr_valorunitario": ["b:ValorUnitario"],
            "nr_preco": ["b:ValorUnitario"],
            "nr_valortotal": ["b:ValorTotal"],
            "cd_viagem": ["b:NumeroAcerto"],
            "cd_motorista": ["b:Motorista", "c:Codigo"],
            "ds_nomemotorista": ["b:Motorista", "c:Nome"],
            "ds_cpf": ["b:Motorista", "c:CPF"],
            "ds_rg": ["b:Motorista", "c:RG"],
            "dt_nascimento": ["b:Motorista", "c:DataNascimento"],
            "ds_estadocivil": ["b:Motorista", "c:EstadoCivil"],
            "ds_enderecomotorista": ["b:Motorista", "c:Endereco", "d:Logradouro"],
            "ds_cidademotorista": ["b:Motorista", "c:Endereco", "d:Cidade", "e:Descricao"],
            "ds_ufmotorista": ["b:Motorista", "c:Endereco", "d:Cidade", "e:SiglaUF"],
            "ds_paismotorista": ["b:Motorista", "c:Endereco", "d:Cidade", "e:Pais", "d:NomePais"],
            "fl_ativo": None
        },
        "flow_carga": {
                "cd_carga": ["b:protocoloIntegracaoCarga"],
                "cd_pedido": ["b:protocoloIntegracaoPedido"]
        },
        "flow_viagem": {
            "cd_viagem": ["b:NumeroAcerto"],
            "dt_inicial": ["b:DataInicialAcerto"],
            "dt_final": ["b:DataFinalAcerto"],
            "nr_kminicial": None,
            "nr_kmfinal": None,
            "nr_hrinicial": None,
            "nr_hrfinal": None,
            "nr_kmrodado": None,
            "nr_horastrabalhadas": None,
            "cd_motorista": ["b:Motoristas", "c:Motorista", "c:Codigo"],
            "ds_nomemotorista": ["b:Motoristas", "c:Motorista", "c:Nome"],
            "ds_cpf": ["b:Motoristas", "c:Motorista", "c:CPF"],
            "ds_rg": ["b:Motoristas", "c:Motorista", "c:RG"],
            "dt_nascimento": ["b:Motoristas", "c:Motorista", "c:DataNascimento"],
            "ds_estadocivil": ["b:Motoristas", "c:Motorista", "c:EstadoCivil"],
            "ds_enderecomotorista": ["b:Motoristas", "c:Motorista", "c:Endereco", "d:Logradouro"],
            "ds_cidademotorista": ["b:Motoristas", "c:Motorista", "c:Endereco", "d:Cidade", "e:Descricao"],
            "ds_ufmotorista": ["b:Motoristas", "c:Motorista", "c:Endereco", "d:Cidade", "e:SiglaUF"],
            "ds_paismotorista": ["b:Motoristas", "c:Motorista", "c:Endereco", "d:Cidade", "e:Pais", "d:NomePais"],
            "cd_veiculo": ["b:Veiculo", "c:Codigo"],
            "ds_placa": ["b:Veiculo", "c:Placa"],
            "ds_nrfrota": ["b:Veiculo", "c:NumeroFrota"],
            "ds_chassi": ["b:Veiculo", "c:NumeroChassi"],
            "ds_renavam": ["b:Veiculo", "c:Renavam"],
            "nr_anofabricacao": ["b:Veiculo", "c:AnoFabricacao"],
            "nr_anomodelo": ["b:Veiculo", "c:AnoModelo"],
            "ds_marca": ["b:Veiculo", "c:Modelo", "c:Marca", "c:Descricao"],
            "ds_modelo": ["b:Veiculo", "c:Modelo", "c:Descricao"],
            "ds_tipoveiculo": ["b:Veiculo", "c:TipoVeiculo"],
            "ds_frota": ["b:Veiculo", "c:SegmentoVeiculo", "c:Descricao"],
            "nr_frota": ["b:Veiculo", "c:NumeroFrota"],
            "dt_aquisicao": ["b:Veiculo", "c:DataAquisicao"],
            "cd_veiculoreboque": ["b:Veiculo", "c:Reboques", "c:Veiculo", "c:Codigo"],
            "ds_placareboque": ["b:Veiculo", "c:Reboques", "c:Veiculo", "c:Placa"],
            "ds_nrfrotareboque": ["b:Veiculo", "c:Reboques", "c:Veiculo", "c:NumeroFrota"],
            "ds_chassireboque": ["b:Veiculo", "c:Reboques", "c:Veiculo", "c:NumeroChassi"],
            "ds_renavamreboque": ["b:Veiculo", "c:Reboques", "c:Veiculo", "c:Renavam"],
            "nr_anofabricacaoreboque": ["b:Veiculo", "c:Reboques", "c:Veiculo", "c:AnoFabricacao"],
            "nr_anomodeloreboque": ["b:Veiculo", "c:Reboques", "c:Veiculo", "c:AnoModelo"],
            "ds_marcareboque": ["b:Veiculo", "c:Reboques", "c:Veiculo", "c:Modelo", "c:Marca", "c:Descricao"],
            "ds_modeloreboque": ["b:Veiculo", "c:Reboques", "c:Veiculo", "c:Modelo", "c:Descricao"],
            "ds_tipoveiculoreboque": ["b:Veiculo", "c:Reboques", "c:Veiculo", "c:TipoVeiculo"],
            "ds_frotareboque": ["b:Veiculo", "c:Reboques", "c:Veiculo", "c:SegmentoVeiculo", "c:Descricao"],
            "nr_frotareboque": ["b:Veiculo", "c:Reboques", "c:Veiculo", "c:NumeroFrota"],
            "dt_aquisicaoreboque": ["b:Veiculo", "c:Reboques", "c:Veiculo", "c:DataAquisicao"],
        },
        "flow_faturamento": {
            "ds_situacao": ["b:SituacaoCTeSefaz"],
            "dt_emissao": ["b:DataEmissao"],
            "nr_valorfrete": ["b:ValorFrete", "c:ValorPrestacaoServico"],
            "nr_valorpedagio": None,
            "nr_valortotal": ["b:ValorFrete", "c:ValorTotalAReceber"],
            "nr_aliqicms": ["b:ValorFrete", "c:ICMS", "d:Aliquota"],
            "nr_km": None,
            "cd_relacionado": ["b:Tomador", "c:CodigoIntegracao"],
            "ds_cnpjcpf": ["b:Tomador", "c:CPFCNPJ"],
            "ds_ierg": ["b:Tomador", "c:RGIE"],
            "ds_nomerazaosocial": ["b:Tomador", "c:RazaoSocial"],
            "ds_nomefantasia": ["b:Tomador", "c:NomeFantasia"],
            "ds_grupo": ["b:Tomador", "c:NomeFantasia"],
            "ds_email": ["b:Tomador", "c:Email"],
            "ds_telefone1": ["b:Tomador", "c:Endereco", "d:Telefone"],
            "ds_telefone2": ["b:Tomador", "c:Endereco", "d:Telefone2"],
            "ds_endereco": ["b:Tomador", "c:Endereco", "d:Logradouro"],
            "ds_cep": ["b:Tomador", "c:Endereco", "d:CEP"],
            "ds_latitude": ["b:Tomador", "c:Endereco", "d:Latitude"],
            "ds_longitude": ["b:Tomador", "c:Endereco", "d:Longitude"],
            "dt_nascfundacao": None,
            "ds_cidade": ["b:Tomador", "c:Endereco", "d:Cidade", "e:Descricao"],
            "ds_uf": ["b:Tomador", "c:Endereco", "d:Cidade", "e:SiglaUF"],
            "ds_pais": ["b:Tomador", "c:Endereco", "d:Cidade", "e:Pais", "d:NomePais"],
            "cd_motorista": ["b:Motoristas", "c:Motorista", "c:Codigo"],
            "ds_nomemotorista": ["b:Motoristas", "c:Motorista", "c:Nome"],
            "ds_cpf": ["b:Motoristas", "c:Motorista", "c:CPF"],
            "ds_rg": ["b:Motoristas", "c:Motorista", "c:RG"],
            "dt_nascimento": ["b:Motoristas", "c:Motorista", "c:DataNascimento"],
            "ds_estadocivil": ["b:Motoristas", "c:Motorista", "c:EstadoCivil"],
            "ds_enderecomotorista": ["b:Motoristas", "c:Motorista", "c:Endereco", "d:Logradouro"],
            "ds_cidademotorista": ["b:Motoristas", "c:Motorista", "c:Endereco", "d:Cidade", "e:Descricao"],
            "ds_ufmotorista": ["b:Motoristas", "c:Motorista", "c:Endereco", "d:Cidade", "e:SiglaUF"],
            "ds_paismotorista": ["b:Motoristas", "c:Motorista", "c:Endereco", "d:Cidade", "e:Pais", "d:NomePais"],
            "cd_veiculo": ["b:Veiculo", "c:Codigo"],
            "ds_placa": ["b:Veiculo", "c:Placa"],
            "ds_nrfrota": ["b:Veiculo", "c:NumeroFrota"],
            "ds_chassi": ["b:Veiculo", "c:NumeroChassi"],
            "ds_renavam": ["b:Veiculo", "c:Renavam"],
            "nr_anofabricacao": ["b:Veiculo", "c:AnoFabricacao"],
            "nr_anomodelo": ["b:Veiculo", "c:AnoModelo"],
            "ds_marca": ["b:Veiculo", "c:Modelo", "c:Marca", "c:Descricao"],
            "ds_modelo": ["b:Veiculo", "c:Modelo", "c:Descricao"],
            "ds_tipoveiculo": ["b:Veiculo", "c:TipoVeiculo"],
            "ds_frota": ["b:Veiculo", "c:SegmentoVeiculo", "c:Descricao"],
            "nr_frota": ["b:Veiculo", "c:NumeroFrota"],
            "dt_aquisicao": ["b:Veiculo", "c:DataAquisicao"],
            "cd_veiculoreboque": ["b:Veiculo", "c:Reboques", "c:Veiculo", "c:Codigo"],
            "ds_placareboque": ["b:Veiculo", "c:Reboques", "c:Veiculo", "c:Placa"],
            "ds_nrfrotareboque": ["b:Veiculo", "c:Reboques", "c:Veiculo", "c:NumeroFrota"],
            "ds_chassireboque": ["b:Veiculo", "c:Reboques", "c:Veiculo", "c:NumeroChassi"],
            "ds_renavamreboque": ["b:Veiculo", "c:Reboques", "c:Veiculo", "c:Renavam"],
            "nr_anofabricacaoreboque": ["b:Veiculo", "c:Reboques", "c:Veiculo", "c:AnoFabricacao"],
            "nr_anomodeloreboque": ["b:Veiculo", "c:Reboques", "c:Veiculo", "c:AnoModelo"],
            "ds_marcareboque": ["b:Veiculo", "c:Reboques", "c:Veiculo", "c:Modelo", "c:Marca", "c:Descricao"],
            "ds_modeloreboque": ["b:Veiculo", "c:Reboques", "c:Veiculo", "c:Modelo", "c:Descricao"],
            "ds_tipoveiculoreboque": ["b:Veiculo", "c:Reboques", "c:Veiculo", "c:TipoVeiculo"],
            "ds_frotareboque": ["b:Veiculo", "c:Reboques", "c:Veiculo", "c:SegmentoVeiculo", "c:Descricao"],
            "nr_frotareboque": ["b:Veiculo", "c:Reboques", "c:Veiculo", "c:NumeroFrota"],
            "dt_aquisicaoreboque": ["b:Veiculo", "c:Reboques", "c:Veiculo", "c:DataAquisicao"],
        },
        "flow_manutencao": {
            "dt_emissao": ["b:DataFechamento"],
            "cd_manutencao": ["b:Codigo"],
            "nr_documento": ["b:Numero"],
            "ds_historico": ["b:Observacao"],
            "nr_kilometragem": ["b:KMAtual"],
            "nr_horimetro": ["b:Horimetro"],
            "nr_valortotal": ["b:ValorRealiazdo"],
            "cd_produto": None,
            "ds_produto": None,
            "ds_ncm": None,
            "ds_undmedida": None,
            "ds_tipomanutencao": ["b:TipoManutencao"],
            "cd_relacionado": ["b:LocalManutencao", "c:CodigoIntegracao"],
            "ds_cnpjcpf": ["b:LocalManutencao", "c:CPFCNPJ"],
            "ds_ierg": ["b:LocalManutencao", "c:RGIE"],
            "ds_nomerazaosocial": ["b:LocalManutencao", "c:RazaoSocial"],
            "ds_nomefantasia": ["b:LocalManutencao", "c:NomeFantasia"],
            "ds_grupo": ["b:LocalManutencao", "c:NomeFantasia"],
            "ds_email": ["b:LocalManutencao", "c:Email"],
            "ds_telefone1": ["b:LocalManutencao", "c:Endereco", "d:Telefone"],
            "ds_telefone2": ["b:LocalManutencao", "c:Endereco", "d:Telefone2"],
            "ds_endereco": ["b:LocalManutencao", "c:Endereco", "d:Logradouro"],
            "ds_cep": ["b:LocalManutencao", "c:Endereco", "d:CEP"],
            "ds_latitude": ["b:LocalManutencao", "c:Endereco", "d:Latitude"],
            "ds_longitude": ["b:LocalManutencao", "c:Endereco", "d:Longitude"],
            "dt_nascfundacao": None,
            "ds_cidade": ["b:LocalManutencao", "c:Endereco", "d:Cidade", "e:Descricao"],
            "ds_uf": ["b:LocalManutencao", "c:Endereco", "d:Cidade", "e:SiglaUF"],
            "ds_pais": ["b:LocalManutencao", "c:Endereco", "d:Cidade", "e:Pais", "d:NomePais"],
            "cd_motorista": ["b:Motorista", "c:Codigo"],
            "ds_nomemotorista": ["b:Motorista", "c:Nome"],
            "ds_cpf": ["b:Motorista", "c:CPF"],
            "ds_rg": ["b:Motorista", "c:RG"],
            "dt_nascimento": ["b:Motorista", "c:DataNascimento"],
            "ds_estadocivil": ["b:Motorista", "c:EstadoCivil"],
            "ds_enderecomotorista": ["b:Motorista", "c:Endereco", "d:Logradouro"],
            "ds_cidademotorista": ["b:Motorista", "c:Endereco", "d:Cidade", "e:Descricao"],
            "ds_ufmotorista": ["b:Motorista", "c:Endereco", "d:Cidade", "e:SiglaUF"],
            "ds_paismotorista": ["b:Motorista", "c:Endereco", "d:Cidade", "e:Pais", "d:NomePais"],
            "cd_veiculo": ["b:Veiculo", "b:Codigo"],
            "ds_placa": ["b:Veiculo", "b:Placa"],
            "ds_nrfrota": ["b:Veiculo", "b:NumeroFrota"],
            "ds_chassi": ["b:Veiculo", "b:NumeroChassi"],
            "ds_renavam": ["b:Veiculo", "b:Renavam"],
            "nr_anofabricacao": ["b:Veiculo", "b:AnoFabricacao"],
            "nr_anomodelo": ["b:Veiculo", "b:AnoModelo"],
            "ds_marca": ["b:Veiculo", "b:Modelo", "b:Marca", "b:Descricao"],
            "ds_modelo": ["b:Veiculo", "b:Modelo", "b:Descricao"],
            "ds_tipoveiculo": ["b:Veiculo", "b:TipoVeiculo"],
            "ds_frota": ["b:Veiculo", "b:SegmentoVeiculo", "b:Descricao"],
            "nr_frota": ["b:Veiculo", "b:NumeroFrota"],
            "dt_aquisicao": ["b:Veiculo", "b:DataAquisicao"],
        },
        "flow_tabelapreco": {
            "cd_tabela": ["b:Codigo"],
            "dt_inicial": ["b:DataInicial"],
            "dt_final": ["b:DataFinal"],
            "nr_valor": ["b:ValorAte"],
            "cd_relacionado": ["b:Posto", "c:CodigoIntegracao"],
            "ds_cnpjcpf": ["b:Posto", "c:CPFCNPJ"],
            "ds_ierg": ["b:Posto", "c:RGIE"],
            "ds_nomerazaosocial": ["b:Posto", "c:RazaoSocial"],
            "ds_nomefantasia": ["b:Posto", "c:NomeFantasia"],
            "ds_grupo": ["b:Posto", "c:NomeFantasia"],
            "ds_email": ["b:Posto", "c:Email"],
            "ds_telefone1": ["b:Posto", "c:Endereco", "d:Telefone"],
            "ds_telefone2": ["b:Posto", "c:Endereco", "d:Telefone2"],
            "ds_endereco": ["b:Posto", "c:Endereco", "d:Logradouro"],
            "ds_cep": ["b:Posto", "c:Endereco", "d:CEP"],
            "ds_latitude": ["b:Posto", "c:Endereco", "d:Latitude"],
            "ds_longitude": ["b:Posto", "c:Endereco", "d:Longitude"],
            "dt_nascfundacao": None,
            "ds_cidade": ["b:Posto", "c:Endereco", "d:Cidade", "e:Descricao"],
            "ds_uf": ["b:Posto", "c:Endereco", "d:Cidade", "e:SiglaUF"],
            "ds_pais": ["b:Posto", "c:Endereco", "d:Cidade", "e:Pais", "d:NomePais"],
            "cd_produto": ["b:Produto", "c:Codigo"],
            "ds_produto": ["b:Produto", "c:Descricao"],
            "ds_ncm": ["b:Produto", "c:NCM"],
        }

    }